### ISSUE TITLE
 pretrained model  for test

### ISSUE THREAD

**Issue by 1235555555shan** [MengyangPu/EDTER#10]
Hello, could you please tell me whether the pre-training model （jx_vit_base_p16_384-83fb41ba.pth    jx_vit_large_p16_384-b3be5167.pth） provided is used for testing, but I will report an error when REloading： model.CLASSES = checkpoint['meta']['CLASSES']
KeyError: 'meta'

or  Still used for training, but no place to load, thank you

**Comment by MengyangPu** [comment]
You can download the model from BaiDuNetdisk:
link==> https://pan.baidu.com/s/1xxkDRUoy9vfO6rtjx_GOqA    (Code:l282)
link==> https://pan.baidu.com/s/1hT1v24H6GjjjjMXqe_Knuw    (Code: skjw)

**Comment by MengyangPu** [comment]
jx_vit_base_p16_384-83fb41ba.pth and jx_vit_large_p16_384-b3be5167.pth are used for training. Please download and put them in the path "/EDTER/pretrain", or modify the load path from line 26-62 in [here](https://github.com/MengyangPu/EDTER/blob/main/mmseg/models/backbones/vit_bimla.py) and [here](https://github.com/MengyangPu/EDTER/blob/main/mmseg/models/backbones/vit_bimla_local8x8.py).

**Comment by 1235555555shan** [comment]
ok, thank you very much ^_^

**Comment by yuuy07** [comment]
> ok, thank you very much ^_^

I have same problem which you encountered, did solve it succefully?
