### ISSUE TITLE
Problem: CUDA out of memory

### ISSUE THREAD

**Issue by icelemon233** [MengyangPu/EDTER#14]
Hello, I get a problem when try to train the model. My GPU device is 3x2080Ti, but it still tell me "out of memory". How to modify the batch size or other measures that help me to solve this problem? Thanks a lot.
By the way, the samples_per_gpu is set to 1. Is it mean that that the batch size is 1?

**Comment by MengyangPu** [comment]
batch size = samples_per_gpu * gpu number.
samples_per_gpu=1 means per gpu can process one image.
Sorry, we use V100 GPU for training, 2080Ti may not be enough. But you can modify the [config files(https://github.com/MengyangPu/EDTER/tree/main/configs/bsds) to reduce the parameters of the model.

**Comment by icelemon233** [comment]
Thank you for your reply. I will try to modify the model to make it fit to my gpus.
A great job. Hope you have a breakthrough in edge detection field~

**Comment by MengyangPu** [comment]
Thanks~
