### ISSUE TITLE
Where can I find the dataset?

### ISSUE THREAD

**Issue by x33rak** [MengyangPu/EDTER#15]
I clicked the link for the dataset but it says the site is under construction. Is there another way in which I can get the dataset?

**Comment by MengyangPu** [comment]
Please download the dataset from [here](https://drive.google.com/file/d/1QgQzujms33qn7-1puoyXAg5VWD4sQ9U-/view?usp=sharing).

**Comment by x33rak** [comment]
thank you

**Comment by liuxingyu123** [comment]
Hello author, the testfg folder is missing in this dataset. Can you provide a complete dataset? I ran to 20000iter and reported an error that the validation set could not be found.

**Comment by x33rak** [comment]
@liuxingyu123 the testfg folder can be found on kaggle under the ground truth folder->test folder through this linkhttps://www.kaggle.com/datasets/balraj98/berkeley-segmentation-dataset-500-bsds500?resource=download.
