### ISSUE TITLE
Can you provide the HHA data?

### ISSUE THREAD

**Issue by wsldy** [MengyangPu/EDTER#25]
EDTER is an excellent work and one of the papers we will cite in the future. We always fail to convert HHA features smoothly during operation, can you provide EDTER's HHA database? Thank you very much

**Comment by MengyangPu** [comment]
Please download the augmented NYUD data (~11GB) from [here](https://pan.baidu.com/s/1J5z6235tv1xef3HXTaqnKg)(Code:t2ce).

**Comment by Bedrettin-Cetinkaya** [comment]
@MengyangPu could you share NYUD data with google drive? 
Thank you very much.

**Comment by MengyangPu** [comment]
Sorry, I don't have enough space to upload the augmented NYUD data.😭😭😭

**Comment by MengyangPu** [comment]
Sorry, I don't have enough space to upload the augmented NYUD data.😭😭😭

> @MengyangPu could you share NYUD data with google drive? Thank you very much.
