### ISSUE TITLE
NYU Dataset training error

### ISSUE THREAD

**Issue by Bedrettin-Cetinkaya** [MengyangPu/EDTER#26]
Hello,

When I tried to run train_local.py for NYU dataset, it gave an error in eval stage and error is:
"fuse_features = local_features * (scale+1) + shift_
RuntimeError: The size of tensor a (552) must match the size of tensor b (559) at non-singleton dimension 3"

How can I solve this error? 

Thanks.

**Comment by Bedrettin-Cetinkaya** [comment]
When I interpolated the tensor to match the size, RGB results are far from yours' : ODS=0.709, OIS=0.725, AP=0.722

**Comment by FengYuQ** [comment]
> When I interpolated the tensor to match the size, RGB results are far from yours' : ODS=0.709, OIS=0.725, AP=0.722

could you tell me how to  interpolated the tensor to match the size？

**Comment by Bedrettin-Cetinkaya** [comment]
> We update the code, please refer [line 385-386,436-437](https://github.com/MengyangPu/EDTER/tree/main/mmseg/models/segmentors/encoder_decoder_local8x8.py).

I used these changes, now training is successfully finished. However, my results, ODS=0.702, OIS=0.718, AP=0.699,  are too lower than the published results. What could be the possible reason for these differences?
