### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 3.81 GiB total capacity; 2.47 GiB already allocated; 49.81 MiB free; 2.55 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by chenguilin111** [MengyangPu/EDTER#36]
File "tools/test.py", line 145, in <module>
    main()
  File "tools/test.py", line 134, in main
    model = MMDistributedDataParallel(
  File "/home/cgl/anaconda3/envs/cu110_torch170/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 412, in __init__
    self._ddp_init_helper()
  File "/home/cgl/anaconda3/envs/cu110_torch170/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 525, in _ddp_init_helper
    self.reducer = dist.Reducer(
RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 3.81 GiB total capacity; 2.47 GiB already allocated; 49.81 MiB free; 2.55 GiB reserved in total by PyTorch)

Maybe my hardware condition does not support me to reproduce your code, can you tell me where to modify the epoch in test code /tools/test.py?

**Comment by chenguilin111** [comment]
> You should modify the batchsize

Thanks for your answer, but I don't know which folder to modify because I'm not familiar with the code. Could you tell me about where and how to change it?

**Comment by Walterkd** [comment]
> 

No, read and try to understand the code yourself, then you can progress.

**Comment by chengyiyi1** [comment]
> > You should modify the batchsize
> 
> Thanks for your answer, but I don't know which folder to modify because I'm not familiar with the code. Could you tell me about where and how to change it?

Bro, have you adjusted it? I haven't found it for a long time. I'd appreciate it if you could tell me
