### ISSUE TITLE
results

### ISSUE THREAD

**Issue by shuttle999** [MengyangPu/EDTER#37]
I use the precomputed results of the BSDS500 dataset you provide to eval, the result is ODS=0.718 OIS=0.763 AP=0.721 R50=0.871 - EDTER, Use parameters such as nms as the same as those used in the EVAL directory that you provide, I just changed the way the data was read from mat to png, Because the results you provide are in png format

But the result given in your paper is ODS=0.840,OIS=0.858,AP=0.896。Of course, I used all 200 pieces of data to eval, please ask the author if there is anything wrong with my method

![image-20221012210826291](https://shuttle1.oss-cn-hangzhou.aliyuncs.com/img/image-20221012210826291.png)

![image-20221012210903104](https://shuttle1.oss-cn-hangzhou.aliyuncs.com/img/image-20221012210903104.png)

**Comment by shuttle999** [comment]
Can you provide the number of pictures and data in mat format that you use for Evaluation? 
Many thanks.

**Comment by MengyangPu** [comment]
http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/BSR/BSR_bsds500.tgz

**Comment by shuttle999** [comment]
OK，I will try it.
Many thanks.
