### ISSUE TITLE
代码复现结果不好

### ISSUE THREAD

**Issue by liuxingyu123** [MengyangPu/EDTER#38]
作者您好，我非常想学习您的这个工作，复现第一阶段的代码有两三个月了，第一阶段的指标一直提不上，我的指标是：ods：0.74116  ois：0.761012   ap：0.736421，和您给的预训练模型的结果相比相差有点大。

我在您第一阶段的代码上做的修改有：

1.环境配置为python=3.7，torch=1.6.0，torchvision=0.7.0，mmcv=1.2.4，mmseg=0.6.0，硬件是a6000，48G

2.由于我只有一个gpu，将launcher设置为none（不使用分布式），总的配置文件设置bachsize=8

3.预训练模型使用的是您代码提供的vit预训练模型的下载地址中下载的，jx_vit_large_p16_384-b3be5167.pth

运行该命令：./tools/dist_train.sh configs/bsds/EDTER_BIMLA_320x320_80k_bsds_bs_8.py 1

我查看了代码中的参数配置和论文中也是一致的。

您知道是哪里出现问题了吗？

我的猜想：我发现在您代码的数据预处理部分

```
img_norm_cfg = dict(
    mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], to_rgb=True)
```

均值是[0.485, 0.456, 0.406],但是我看其他边缘检测代码中bsds的图片均值是[104.00699, 116.66877, 122.67892],是不是这里的问题？

如果可以的话能给我发一份您训练的日志文件吗，我想看看损失收敛情况，我的邮箱是[1610218295@qq.com](mailto:1610218295@qq.com)，非常感谢。

**Comment by shuttle999** [comment]
请问你使用作者的预训练模型测试的结果精度指标是多少呢？我最近也是在学习作者的工作，但是我发现我的指标一直对不上，不知道是不是我的验证代码出了问题？

**Comment by shuttle999** [comment]
你是使用作者给出的模型文件进行预测然后使用mat文件进行验证吗？我使用的是作者提供的png格式的结果图片进行验证，然后修改验证代码的读取部分，可能是我那个地方修改出了问题。

**Comment by liuxingyu123** [comment]
> 你是使用作者给出的模型文件进行预测然后使用mat文件进行验证吗？我使用的是作者提供的png格式的结果图片进行验证，然后修改验证代码的读取部分，可能是我那个地方修改出了问题。

是的，必须使用mat文件来生成png。

**Comment by shuttle999** [comment]
好的，谢谢你，我再去尝试使用mat进行验证

**Comment by wuwen1994** [comment]
> > 你是使用作者给出的模型文件进行预测然后使用mat文件进行验证吗？我使用的是作者提供的png格式的结果图片进行验证，然后修改验证代码的读取部分，可能是我那个地方修改出了问题。
> 
> 是的，必须使用mat文件来生成png。

你好，请问test.txt中的mat是BSDS数据集自带的mat文件么，为什么我这显示识别不了文件

**Comment by MengyangPu** [comment]
We fixed and updated the codes, please redownload and run, thanks~

**Comment by liuxingyu123** [comment]
> We fixed and updated the codes, please redownload and run, thanks~

thank you very much ,i get it.

**Comment by yun-liu** [comment]
Have anyone reproduced the results? Could you share how to do it?

**Comment by liuxingyu123** [comment]
> 
My environment is Python 3.8, Pytorch 1.7, and mvcc 1.2.4. The first stage of reproduction has an ODS of 0.812. The code has not been changed, and I only have one GPU. Therefore, during training, the parameter specifies that the number of GPUs is 1.
