### ISSUE TITLE
Cannot download pre-trained models

### ISSUE THREAD

**Issue by domingoshell** [MengyangPu/EDTER#39]
I can't download any pre-trained model file from BaiDuNetdisk. Can you please make those available to download in Google Drive, just like results folder?

**Comment by mhermkrtchyan** [comment]
Yes, I also tried to download it. Writes that there is no permission to download.

**Comment by MengyangPu** [comment]
Please download the pre-trained model from: https://drive.google.com/drive/folders/1OkdakKKIMRGnKH8mxuFi_qI9sa903CD2?usp=share_link.
