### ISSUE TITLE
No CLASS in checkppoint?

### ISSUE THREAD

**Issue by xujie98** [MengyangPu/EDTER#43]
Thanks for the excellent work and I have been tracing RINDNet and EDTER for several months. Here I used pre-trained model and have the error showed below.

Traceback (most recent call last):
  File "tools/test.py", line 139, in <module>
    main()
  File "tools/test.py", line 121, in main
    model.CLASSES = checkpoint['meta']['CLASSES']
KeyError: 'meta'

Here is my set in tools/set.py
20     parser = argparse.ArgumentParser(description='mmseg test (and eval) a model')
 21     parser.add_argument('--config', type=str, default='configs/nyud/EDTER_BIMLA_320x320_40k_nyud_hha_bs_4.py', help='trai    n config file path')
 22     parser.add_argument('--checkpoint', type=str, default='/home/EDTER-main/pretrain/jx_vit_large_p16_384-b3be5167.pth')

I have checked the variable "chekpoint" no keys named meta or CLASS in the checkpoint.  I am looking forward to your reply. Thank you in advance！

**Comment by MengyangPu** [comment]
Please download the checkpoint from [here](https://github.com/MengyangPu/EDTER#download-pre-trained-model).
"jx_vit_large_p16_384-b3be5167.pth" is the initial weights.

**Comment by xujie98** [comment]
谢谢您的回复，我再试一下。

**Comment by yuuy07** [comment]
您好，我遇到了和您相同的问题，请问你是如何解决的

**Comment by xujie98** [comment]
> 您好，我遇到了和您相同的问题，请问你是如何解决的

作者给出了参考，可以尝试。我后来因为其他事情没有继续。
