### ISSUE TITLE
concerning the NYUD2 dataset

### ISSUE THREAD

**Issue by Daniellli** [MengyangPu/EDTER#44]
Thank you for such a contribution. 

I am wondering how to get the full version of NYUD2 datasets, or how you process the origin NYUD2 to generate the current resolution.  

again, thank you for your contribution and attention. look forward your reply.

**Comment by MengyangPu** [comment]
Please refer to [issue#25](https://github.com/MengyangPu/EDTER/issues/25#issuecomment-1214932282).
