### ISSUE TITLE
预测结果可视化

### ISSUE THREAD

**Issue by 1411655232** [MengyangPu/EDTER#45]
你好，请问怎么可视化模型的预测结果
我运行python tools/test_local.py --show指令时 会报AttributeError: 'EncoderDecoder_LOCAL8x8' object has no attribute 'CLASSES'的错误

**Comment by LSC200107** [comment]
把13-16行的注释取消就可以了，我也遇到了同样的问题。

**Comment by 1411655232** [comment]
> 把13-16行的注释取消就可以了，我也遇到了同样的问题。

请问你能正常验证吗

**Comment by LSC200107** [comment]
可以



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 下午4:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MengyangPu/EDTER] 预测结果可视化 (Issue #45)





  
把13-16行的注释取消就可以了，我也遇到了同样的问题。
  
请问你能正常验证吗
