### ISSUE TITLE
Calculation of AP metric

### ISSUE THREAD

**Issue by Bedrettin-Cetinkaya** [MengyangPu/EDTER#47]
Hello,
When I ran your evaluation matlab script, I got the results: ODS=0.774, OIS=0.789, AP=0.756 using your pre-computed nms images for NYUD-RGB. However, you reported an AP metric of 79.7, there is a considerable difference between these results. When I checked the AP array, I noticed that your results didn't have results for recall value >= 0.9, and you interpolated AP for these missing values. The following figure is taken from your supplementary material, and I show these missing AP values with a black rectangle.
![image](https://user-images.githubusercontent.com/28837795/222693891-ad92e477-2110-4948-9e35-7af9f1df7d18.png)

I wonder if this is how you calculate AP. 
Thanks.

**Comment by MengyangPu** [comment]
Please refer to our [eval code](https://github.com/MengyangPu/EDTER/tree/main/eval), thanks~
