### ISSUE TITLE
The code about sampling the image in Stage 2 as described in essay

### ISSUE THREAD

**Issue by Kaacoinnn** [MengyangPu/EDTER#49]
Has anyone found the code about how to sample the image into 4 regions as described in Stage 2 and the process that send the sampled image into local transformer??????
In which code file that i can find the solution.  If you know, please just leave a meassage!!!

**Comment by MengyangPu** [comment]
[sample the image into 4 regions](https://github.com/MengyangPu/EDTER/blob/9e9df6764ef08c14226a2914b58ea5dc416e9e19/mmseg/models/segmentors/encoder_decoder_local8x8.py#L173)

[send the sampled image into local transformer](https://github.com/MengyangPu/EDTER/blob/9e9df6764ef08c14226a2914b58ea5dc416e9e19/mmseg/models/segmentors/encoder_decoder_local8x8.py#L215)

**Comment by Kaacoinnn** [comment]
THX for replying!!! That's helps a lot!
