### ISSUE TITLE
MMCV is  incompatible

### ISSUE THREAD

**Issue by lgwsgc** [MengyangPu/EDTER#50]
Can you tell me what version of Torch I have installed? I am using Torch version 1.13.1, but I encountered an error when trying to install mmcv==1.7.1, which I downloaded based on the corresponding version information provided on the mmcv official website。error asfollows：
 MMCV==1.7.0 is used but incompatible. Please install mmcv>=[1, 1, 2], <=[1, 2, 7].

**Comment by MengyangPu** [comment]
conda install pytorch=1.6.0 torchvision cudatoolkit=10.1 -c pytorch -y
pip install mmcv-full==1.2.2 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html

**Comment by lgwsgc** [comment]
> conda install pytorch=1.6.0 torchvision cudatoolkit=10.1 -c pytorch -y pip install mmcv-full==1.2.2 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html

thank you
