### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by kulkarnikeerti** [MengyangPu/EDTER#52]
Hi @MengyangPu 

Can you help with this error.
I followed the below steps:
```
pip install -r requirements.txt
pip install mmcv
pip install mmsegmentation
```
And I get the mentioned error when I run `python tools/test.py`

I am using:
```
Ubuntu 22.04
GCC: 9.5.0 (default was 11.3 but I changed it to 9 assuming it would work)
Python: 3.10.6
CUDA: 11.4
Torch: '1.13.1+cu117'
```

Thanks in advance

**Comment by MengyangPu** [comment]
Maybe you can refer to the [installation](https://github.com/fudan-zvg/SETR).

**Comment by kulkarnikeerti** [comment]
I was able to resolve the issue by downgrading the Gcc version to 9 and fresh installation of Pytorch, Mmcv and Mmsegmentation. After many trail and errors with versions it was resolved. Thanks
