### ISSUE TITLE
KeyError: 'BSDSDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by kulkarnikeerti** [MengyangPu/EDTER#53]
Hi @MengyangPu 

How do I resolve this issue?

Thanks in advance

**Comment by MengyangPu** [comment]
Sorry, I do not have such a problem, could you provide more details？

**Comment by JingDongdong** [comment]
Hi @kulkarnikeerti 
I have the same problem.Do you have a solution?

**Comment by kulkarnikeerti** [comment]
@MengyangPu 
More details: I am trying to run python tools/test.py with BSDS dataset. I downloaded the dataset [from this link](https://github.com/MengyangPu/EDTER/issues/15#issuecomment-1168181704). I installed all the dependencies required for the script to run. Below you can find the complete error. 

```
Traceback (most recent call last):
  File "tools/test.py", line 139, in <module>
    main()
  File "tools/test.py", line 110, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/keerti/anaconda3/envs/edter_conda/lib/python3.7/site-packages/mmseg/datasets/builder.py", line 85, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/keerti/anaconda3/envs/edter_conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'BSDSDataset is not in the dataset registry'

Please let me know if you need to know anything else to understand the issue. Thanks

```

**Comment by kulkarnikeerti** [comment]
> Hi @kulkarnikeerti I have the same problem.Do you have a solution?

No, I still have the same issue!

**Comment by kulkarnikeerti** [comment]
> Sorry, I do not have such a problem, could you provide more details？

@MengyangPu 
More details: I am trying to run python tools/test.py with BSDS dataset. I downloaded the dataset [from this link](https://github.com/MengyangPu/EDTER/issues/15#issuecomment-1168181704). I installed all the dependencies required for the script to run. Below you can find the complete error. 

```
Traceback (most recent call last):
  File "tools/test.py", line 139, in <module>
    main()
  File "tools/test.py", line 110, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/keerti/anaconda3/envs/edter_conda/lib/python3.7/site-packages/mmseg/datasets/builder.py", line 85, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/keerti/anaconda3/envs/edter_conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'BSDSDataset is not in the dataset registry'
```

Please let me know if you need to know anything else to understand the issue. Thanks

**Comment by kulkarnikeerti** [comment]
@MengyangPu @JingDongdong 

Okay, so I figured out what was the issue. So, I had different version of mmcv installed in my system and for the test and train it was using different version. So the one which was used during test didn't have the dataset included in the registry. So I just replaced two versions with one and the issue is resolved. But I have different problem now which you can find [here](https://github.com/MengyangPu/EDTER/issues/56). It would be of great help if you can help me with this.

**Comment by hzhao1997** [comment]
pip uninstall mmsegmentation and add 
`import sys`
`sys.path.append('.')`
before 
`from mmseg.apis import multi_gpu_test, single_gpu_test`
`from mmseg.datasets import build_dataloader, build_dataset`
`from mmseg.models import build_segmentor` 
will help.
