### ISSUE TITLE
How to change batch_size?

### ISSUE THREAD

**Issue by kulkarnikeerti** [MengyangPu/EDTER#55]
Hi @MengyangPu 

I would like to change the `batch_size` or similar metric in this model during training. Because, I get the below error when I run `train_dist.sh` with bsds dataset. Therefore I would like to test if everything works fine without any issues with the minimal number of runs(batch size) and then upload and run it in server when i am sure there are no further issues.

`RuntimeError: CUDA out of memory. Tried to allocate 3.52 GiB (GPU 0; 7.80 GiB total capacity; 5.02 GiB already allocated; 1.21 GiB free; 5.50 GiB reserved in total by PyTorch)`

Thanks in advance

**Comment by yuuy07** [comment]
Hello, did you get the way to change batchsize?When I use his pretrain model, I have meet this error, so I have to train model by myself

**Comment by MengyangPu** [comment]
batch size = samples_per_gpu * gpu number.  For example, if you use one v100 gpu for training, please set "samples_per_gpu=8" and "gpu number=1".
Please modify "samples_per_gpu" in [configs files](https://github.com/MengyangPu/EDTER/tree/main/configs/bsds).
