### ISSUE TITLE
NYUD dataset download?

### ISSUE THREAD

**Issue by kulkarnikeerti** [MengyangPu/EDTER#58]
Hi @MengyangPu 

I have problem with BSDS dataset and I cannot train or test the model. Therefore, I would like to test the model with `NYUD` dataset. I tried to download the dataset from the given link. But, I see the dataset is in `.rpm` and `.deb` format. I am struggling to extract data from these files. Can you help me with this? Or suggest me to go in the correct direction. 

Thanks

**Comment by hhqweasd** [comment]
The author of RCF provided the download link of NYUD dataset, and we downloaded it using the link provided by @yun-liu. For more information, please refer to [this link](https://github.com/yun-liu/RCF/issues/126).
