### ISSUE TITLE
Why do the predictions have clear dividing lines?

### ISSUE THREAD

**Issue by zjuPeco** [MengyangPu/EDTER#59]
Hello, I run the model with pretrained weights on BSDS-500 testset. The ODS value is all right, but the visual results have clear dividing lines which is not seen in the prediction of other models.

Can you explain this? 

Thank you!

![2018_concat](https://user-images.githubusercontent.com/25611711/226781271-d7f86b6c-3ce2-457d-b86a-e99308eca7c1.png)

**Comment by zjuPeco** [comment]
using "whole" mode instead of "slide" to inference solves this problem

**Comment by lixianshen20** [comment]
你好，whole模式是什么意思哇

**Comment by zjuPeco** [comment]
> 你好，whole模式是什么意思哇

test_cfg = dict(mode='slide', crop_size=(320, 320), stride=(280, 280))

**Comment by zjuPeco** [comment]
> 你好，whole模式是什么意思哇

https://github.com/MengyangPu/EDTER/blob/main/configs/bsds/EDTER_BIMLA_320x320_80k_bsds_bs_8.py#L97

```python
test_cfg = dict(mode='slide', crop_size=(320, 320), stride=(280, 280))
```

to 

```python
test_cfg = dict(mode='whole')
```

**Comment by lixianshen20** [comment]
thanks very much!!

**Comment by lixianshen20** [comment]
你好！在whole模型下，此模型的输入为320*320，如果要输入的数据和320不匹配，只能选择slide模式吗？不知道我这样理解对不对
