### ISSUE TITLE
Can you explain how to use the model weights for the two stages in the paper？

### ISSUE THREAD

**Issue by lixianshen20** [MengyangPu/EDTER#60]
There are two training stages in the paper, corresponding to two model training weights. What should I do with checkpoints when testing tools/test.py?Thank you in advance

**Comment by MengyangPu** [comment]
Please modify the path to load the stage I model in https://github.com/MengyangPu/EDTER/blob/de6438b82a1049f8b45ceb10f9137072151c1d17/tools/test_local.py#L26, and modify the path to load the stage II model in https://github.com/MengyangPu/EDTER/blob/de6438b82a1049f8b45ceb10f9137072151c1d17/tools/test_local.py#L24C66-L24C70.
