### ISSUE TITLE
爆内存

### ISSUE THREAD

**Issue by Mamaka2020** [MengyangPu/EDTER#62]
您好，我的第二阶段训练老是爆内存，请问您是怎么多卡训练的？

![image](https://user-images.githubusercontent.com/53122111/229329604-ad665b57-d04d-4fe2-b285-e674cc01aaac.png)

**Comment by yuuy07** [comment]
他三张V100 32G的，我们得调低点参数才行

**Comment by hhqweasd** [comment]
代码使用的是NVIDIA V100-32G GPU，其他型号的显卡出现显存不足的问题需要调整相关超参数才能成功运行哈
