### ISSUE TITLE
ODS和OIS是用哪一块代码计算的呢？

### ISSUE THREAD

**Issue by zhangyongzhuang** [MengyangPu/EDTER#63]
ODS和OIS是用哪一块代码计算的呢？我在项目中没有找到，还请解答一下，谢谢。

**Comment by MengyangPu** [comment]
在eval文件夹下

**Comment by hhqweasd** [comment]
评估代码路径在这儿哈，https://github.com/MengyangPu/EDTER/tree/main/eval，都是mallab的代码

**Comment by zhangyongzhuang** [comment]
> 在eval文件夹下

谢谢

**Comment by zhangyongzhuang** [comment]
> 评估代码路径在这儿哈，https://github.com/MengyangPu/EDTER/tree/main/eval 都是mallab的代码

谢谢

**Comment by Raiden-cn** [comment]
出ODS和OIS的代码有人移植到python上过吗
