### ISSUE TITLE
MMCV==1.2.2 is used but incompatible. Please install mmcv>=2.0.0rc4.

### ISSUE THREAD

**Issue by loyevei** [MengyangPu/EDTER#64]
Hi, I've tried to test the pretrained model.
I set environments as follows:
python=3.7.7
conda install pytorch=1.6.0 torchvision cudatoolkit=10.1 -c pytorch -y
pip install mmcv-full==1.2.2 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html

But when I run the code, I got this error. Can you tell me how can I solve this error? Thank you in advance for your help :)

$ python tools/test.py

Traceback (most recent call last):
  File "tools/test.py", line 10, in <module>
    from mmseg.apis import multi_gpu_test, single_gpu_test
  File "/home/loyevei/.local/lib/python3.7/site-packages/mmseg/__init__.py", line 62, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.2.2 is used but incompatible. Please install mmcv>=2.0.0rc4.

**Comment by hhqweasd** [comment]
Please check your enviroment, especially the cuda/torch version. A lower version of PyTorch may be required.
