### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by geek-APTX4869** [MengyangPu/EDTER#65]
预训练模型是不是multi-scale测试的情况呢

**Comment by githublqs** [comment]
请问您有成功复现论文的效果吗

**Comment by hhqweasd** [comment]
预训练模型目前上传的是multi-scale + voc 的结果哈

**Comment by hhqweasd** [comment]
> 请问您有成功复现论文的效果吗

复现的话可以参考一下这条[回复](https://github.com/MengyangPu/EDTER/issues/28#issuecomment-1694700529)，看看环境、机器、命令跟您的有没有出入哈
