### ISSUE TITLE
关于硬件资源不足，修改网络输入参数宽高，无法复现和预训练一样好效果的问题

### ISSUE THREAD

**Issue by githublqs** [MengyangPu/EDTER#66]
![图片](https://github.com/MengyangPu/EDTER/assets/4864431/81ce814d-02cb-4a9a-a6bb-54ebf6716d83)

**Comment by hhqweasd** [comment]
硬件不足大概率得到最好结果的，最好还是硬件上足了。如果硬件实在是不够，你只是调整网络输入参数宽高是不行的，训练的时候还要看看模型收敛的怎么样，根据结果调整其他超参数，这样才能得到一个比较好的结果。

**Comment by MengyangPu** [comment]
修改网络输入参数宽高会导致模型无法学习整张图像的全局信息，因此会大大降低模型的准确率。
