### ISSUE TITLE
Testing_local

### ISSUE THREAD

**Issue by wangxiang-wx** [MengyangPu/EDTER#74]
Testing started at 15:19 ...
Launching pytest with arguments E:\EDTER_Edge_detection\EDTER-main\test_local.py --no-header --no-summary -q in E:\EDTER_Edge_detection\EDTER-main

============================= test session starts =============================
collecting ... collected 0 items

============================ no tests ran in 1.42s ============================

Process finished with exit code 5

Empty suite

**Comment by hhqweasd** [comment]
“collected 0 items” seems to indicate that the code didn't read any testing data. Can you print the path to see if there is testing data?

**Comment by wangxiang-wx** [comment]
Sorry, I found out that my path was incorrect after changing the IDE. Now, the problem has been resolved at. Thank you for your outstanding contribution
