### ISSUE TITLE
the size of BSDS dataset

### ISSUE THREAD

**Issue by yr-wang** [MengyangPu/EDTER#77]
hello，according to the link in the readme file, the BSDS dataset I downloaded was only 70MB instead of 12GB，why is it so small？
![image](https://github.com/MengyangPu/EDTER/assets/55644709/17bc30b7-fd25-4bc9-b7e4-51f3cc8973ca)
![image](https://github.com/MengyangPu/EDTER/assets/55644709/cc2214e1-8a5e-4bb7-ba48-a605dd437665)

**Comment by MengyangPu** [comment]
Download the augmented BSDS data (1.2GB) from (https://vcl.ucsd.edu/hed/HED-BSDS.tar).[1]
[1] https://github.com/s9xie/hed#training-hed

**Comment by yr-wang** [comment]
> Download the augmented BSDS data (1.2GB) from (https://vcl.ucsd.edu/hed/HED-BSDS.tar). [1] [1] https://github.com/s9xie/hed#training-hed

Thank you very much for your enthusiastic help！
