### ISSUE TITLE
Poor metrics for training the nyud-hha dataset

### ISSUE THREAD

**Issue by liuxingyu123** [MengyangPu/EDTER#80]
Hello, I used configuration file of EDTER_BIMLA_320x320_40k_nyud_hha_bs_4.py directly when training the nyud hha dataset. After training, the test is conducted with ods=0.640. May I ask what parameters need to be changed during training?

**Comment by MengyangPu** [comment]
After testing NYUD-HHA-StageI, we get ODS=0.690, OIS=0.707.
We upload all files to [BaiDuNetdisk](https://pan.baidu.com/s/1iUUyJRtBw7lLZRLIrJe36w?pwd=6a98). You can change the parameters following the training logs. Thanks~

**Comment by MengyangPu** [comment]
NYUD-HHA-StageII can be download from (here)[https://pan.baidu.com/s/1TmZFoaOMIKvApMSTVDoT6A?pwd=6mwu]
