### ISSUE TITLE
failed to load global model from the pretained model

### ISSUE THREAD

**Issue by Chi-Mz** [MengyangPu/EDTER#82]
Hi author and other friends,  If I want to test EDTER-Stage II,  how should I set the argument 'checkpoint' and 'global-checkpoint', all of them should be set same ?

**Comment by MengyangPu** [comment]
https://github.com/MengyangPu/EDTER#3-testing

**Comment by Chi-Mz** [comment]
> https://github.com/MengyangPu/EDTER#33-edter-stage-ii-with-single-scale-testing

thanks for your reply, I have read the content of the link, but I have some confused, how should I download the pretrained model "iter_XXXXX.pth" for checkpoint and globalcheckpoint. I have download the 'EDTER-BSDS-VOC-StageII' model

**Comment by MengyangPu** [comment]
parser.add_argument('--checkpoint', type=str, default='/your path........../EDTER-BSDS-VOC-StageII.pth', 
                     help='the dir of local model')
parser.add_argument('--global-checkpoint', type=str, 
                     default='/your path........../EDTER-BSDS-VOC-StageI.pth', 
                     help='the dir of global model')

**Comment by Chi-Mz** [comment]
> parser.add_argument('--checkpoint', type=str, default='/your path........../EDTER-BSDS-VOC-StageII.pth', help='the dir of local model') parser.add_argument('--global-checkpoint', type=str, default='/your path........../EDTER-BSDS-VOC-StageI.pth', help='the dir of global model')

thanks again, I have load the pretrained model successfully
