### ISSUE TITLE
关于eval代码

### ISSUE THREAD

**Issue by AlbertTJU** [MengyangPu/EDTER#92]
我注意到您在BSDS500\Multicue和NYUD数据集上的测试代码并不完全一样，主要是edgesNmsMex这一行，请问为何需要改变这个函数里边的参数呢？如果按照同样的参数来进行评估，是否会有很大的影响呢？非常期待您的回复！

**Comment by MengyangPu** [comment]
@AlbertTJU 你好，测试代码的参数参考的别人的设置。修改参数应该会有影响，但并不大。

**Comment by AlbertTJU** [comment]
> @AlbertTJU 你好，测试代码的参数参考的别人的设置。修改参数应该会有影响，但并不大。

好的，感谢您的回复！
