### ISSUE TITLE
test local load checkpoint error

### ISSUE THREAD

**Issue by ZZZZZZHE** [MengyangPu/EDTER#94]
dear author , when i  run the test_local.py some  bug come out about the checkpoint load , i want to know how i set the args,i download the following models
![image](https://github.com/MengyangPu/EDTER/assets/34742752/89830276-5b80-4d76-898c-38f8e63ce007)
and the args i set is:
![image](https://github.com/MengyangPu/EDTER/assets/34742752/4d97dea1-5419-4d86-9186-8800928f8c10)
add the bug is the model didnt load success:
![image](https://github.com/MengyangPu/EDTER/assets/34742752/aee4cea8-b9c0-43b4-b2bb-21831fe21988)
i think the bug is i didnt set the args right,can you tell me how to solve it ,thanks  for reply

**Comment by MengyangPu** [comment]
@ZZZZZZHE 
parser.add_argument('--global-checkpoint', type=str,
                        default='D：\百度下载 EDIER-main\pretrain\EDTER-BSDS-VOC-StageI.pth"',
                        help='the dir of global model')
