### ISSUE TITLE
eval_bsds.m 中的data_dir是什么文件的地址？

### ISSUE THREAD

**Issue by Muzi010** [MengyangPu/EDTER#95]

**Comment by MengyangPu** [comment]
Your predicted results (.mat files).

**Comment by Muzi010** [comment]
Thanks, is that to convert the png format image from the test set run to a .mat format file? Do you have the code to convert the data format or more complete information on the metrics to perform the evaluation?

**Comment by Muzi010** [comment]
thank you

**Comment by Muzi010** [comment]
I have another question, I have run the PR curves for a single model, how do I run the results for multiple models?
